[package]
name = "npm-flip"
version = "0.1.0"
authors = ["Ava Howell <ava@avahowell.me>"]

[dependencies]
rand = "0.3"
futures = "0.1.14"
hyper = "0.11"
tokio-core = "0.1"
serde_json = "1.0"

[[bin]]
name = "npm-flip"
path = "main.rs"
